# Generated by Django 4.2.1 on 2023-05-28 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projName', models.CharField(max_length=50)),
                ('projDesc', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('projStatus', models.CharField(max_length=20)),
            ],
        ),
    ]
