# Generated by Django 4.2.1 on 2023-05-30 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assignee_finances_resource_project_manager_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ResourceID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availableHours', models.IntegerField(blank=True, default=0, null=True)),
                ('plannedEffort', models.IntegerField(blank=True, default=0, null=True)),
                ('actualEffort', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('financeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('margin', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
    ]
