# Generated by Django 4.2.1 on 2023-05-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_resource_finances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='base.project'),
        ),
    ]
