# Generated by Django 4.2.1 on 2024-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_resource_finances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
